package com.ippteam.fish.dao;

import com.ippteam.fish.entity.Developer;
import com.ippteam.fish.entity.DeveloperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("DeveloperDao")
public interface DeveloperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    long countByExample(DeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    int deleteByExample(DeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    int insert(Developer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    int insertSelective(Developer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    List<Developer> selectByExample(DeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") Developer record, @Param("example") DeveloperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    int updateByExample(@Param("record") Developer record, @Param("example") DeveloperExample example);
}