package com.ippteam.fish.entity;

public class Developer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.id
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.app_key
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    private String appKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.security_key
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    private String securityKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.id
     *
     * @return the value of developer.id
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.id
     *
     * @param id the value for developer.id
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.app_key
     *
     * @return the value of developer.app_key
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.app_key
     *
     * @param appKey the value for developer.app_key
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.security_key
     *
     * @return the value of developer.security_key
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    public String getSecurityKey() {
        return securityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.security_key
     *
     * @param securityKey the value for developer.security_key
     *
     * @mbg.generated Wed Nov 02 11:23:55 CST 2016
     */
    public void setSecurityKey(String securityKey) {
        this.securityKey = securityKey == null ? null : securityKey.trim();
    }
}