package com.ippteam.fish.entity;

import java.util.Date;

public class Developer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.id
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.app_key
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    private String appKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.security_key
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    private String securityKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.create_time
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.update_time
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.id
     *
     * @return the value of developer.id
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.id
     *
     * @param id the value for developer.id
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.app_key
     *
     * @return the value of developer.app_key
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.app_key
     *
     * @param appKey the value for developer.app_key
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.security_key
     *
     * @return the value of developer.security_key
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public String getSecurityKey() {
        return securityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.security_key
     *
     * @param securityKey the value for developer.security_key
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public void setSecurityKey(String securityKey) {
        this.securityKey = securityKey == null ? null : securityKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.create_time
     *
     * @return the value of developer.create_time
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.create_time
     *
     * @param createTime the value for developer.create_time
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.update_time
     *
     * @return the value of developer.update_time
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.update_time
     *
     * @param updateTime the value for developer.update_time
     *
     * @mbg.generated Thu Nov 03 21:55:42 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}