package com.ippteam.fish.entity;

import java.util.ArrayList;
import java.util.List;

public class OauthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public OauthExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andOauthNameIsNull() {
            addCriterion("oauth_name is null");
            return (Criteria) this;
        }

        public Criteria andOauthNameIsNotNull() {
            addCriterion("oauth_name is not null");
            return (Criteria) this;
        }

        public Criteria andOauthNameEqualTo(String value) {
            addCriterion("oauth_name =", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameNotEqualTo(String value) {
            addCriterion("oauth_name <>", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameGreaterThan(String value) {
            addCriterion("oauth_name >", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameGreaterThanOrEqualTo(String value) {
            addCriterion("oauth_name >=", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameLessThan(String value) {
            addCriterion("oauth_name <", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameLessThanOrEqualTo(String value) {
            addCriterion("oauth_name <=", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameLike(String value) {
            addCriterion("oauth_name like", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameNotLike(String value) {
            addCriterion("oauth_name not like", value, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameIn(List<String> values) {
            addCriterion("oauth_name in", values, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameNotIn(List<String> values) {
            addCriterion("oauth_name not in", values, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameBetween(String value1, String value2) {
            addCriterion("oauth_name between", value1, value2, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthNameNotBetween(String value1, String value2) {
            addCriterion("oauth_name not between", value1, value2, "oauthName");
            return (Criteria) this;
        }

        public Criteria andOauthIdIsNull() {
            addCriterion("oauth_id is null");
            return (Criteria) this;
        }

        public Criteria andOauthIdIsNotNull() {
            addCriterion("oauth_id is not null");
            return (Criteria) this;
        }

        public Criteria andOauthIdEqualTo(String value) {
            addCriterion("oauth_id =", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdNotEqualTo(String value) {
            addCriterion("oauth_id <>", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdGreaterThan(String value) {
            addCriterion("oauth_id >", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdGreaterThanOrEqualTo(String value) {
            addCriterion("oauth_id >=", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdLessThan(String value) {
            addCriterion("oauth_id <", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdLessThanOrEqualTo(String value) {
            addCriterion("oauth_id <=", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdLike(String value) {
            addCriterion("oauth_id like", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdNotLike(String value) {
            addCriterion("oauth_id not like", value, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdIn(List<String> values) {
            addCriterion("oauth_id in", values, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdNotIn(List<String> values) {
            addCriterion("oauth_id not in", values, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdBetween(String value1, String value2) {
            addCriterion("oauth_id between", value1, value2, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthIdNotBetween(String value1, String value2) {
            addCriterion("oauth_id not between", value1, value2, "oauthId");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenIsNull() {
            addCriterion("oauth_access_token is null");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenIsNotNull() {
            addCriterion("oauth_access_token is not null");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenEqualTo(String value) {
            addCriterion("oauth_access_token =", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenNotEqualTo(String value) {
            addCriterion("oauth_access_token <>", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenGreaterThan(String value) {
            addCriterion("oauth_access_token >", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("oauth_access_token >=", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenLessThan(String value) {
            addCriterion("oauth_access_token <", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("oauth_access_token <=", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenLike(String value) {
            addCriterion("oauth_access_token like", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenNotLike(String value) {
            addCriterion("oauth_access_token not like", value, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenIn(List<String> values) {
            addCriterion("oauth_access_token in", values, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenNotIn(List<String> values) {
            addCriterion("oauth_access_token not in", values, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenBetween(String value1, String value2) {
            addCriterion("oauth_access_token between", value1, value2, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthAccessTokenNotBetween(String value1, String value2) {
            addCriterion("oauth_access_token not between", value1, value2, "oauthAccessToken");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresIsNull() {
            addCriterion("oauth_expires is null");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresIsNotNull() {
            addCriterion("oauth_expires is not null");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresEqualTo(Integer value) {
            addCriterion("oauth_expires =", value, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresNotEqualTo(Integer value) {
            addCriterion("oauth_expires <>", value, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresGreaterThan(Integer value) {
            addCriterion("oauth_expires >", value, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresGreaterThanOrEqualTo(Integer value) {
            addCriterion("oauth_expires >=", value, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresLessThan(Integer value) {
            addCriterion("oauth_expires <", value, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresLessThanOrEqualTo(Integer value) {
            addCriterion("oauth_expires <=", value, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresIn(List<Integer> values) {
            addCriterion("oauth_expires in", values, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresNotIn(List<Integer> values) {
            addCriterion("oauth_expires not in", values, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresBetween(Integer value1, Integer value2) {
            addCriterion("oauth_expires between", value1, value2, "oauthExpires");
            return (Criteria) this;
        }

        public Criteria andOauthExpiresNotBetween(Integer value1, Integer value2) {
            addCriterion("oauth_expires not between", value1, value2, "oauthExpires");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 07 15:45:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth
     *
     * @mbg.generated Tue Feb 07 15:45:54 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}